# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git’
platform :ios, '10.0'

use_frameworks!
target 'YourTargetApp' do
  pod 'AEPCore'
  pod 'AEPLifecycle'
  pod 'AEPIdentity'
  pod 'AEPSignal'
  pod 'AEPRulesEngine'
end
